<?php

namespace Database\Seeders;

use App\Models\Insumo;
use App\Models\MovimientoInventario;
use App\Models\Producto;
use App\Models\Receta;
use App\Models\User;
use Illuminate\Database\Seeder;

class InventarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::first();

        // 1. Catálogo de Insumos / Materias Primas para Restaurante General
        $insumosData = [
            [
                'nombre' => 'Lomo Fino de Res Angus',
                'codigo' => 'SKU-CAR-01',
                'categoria' => 'carnes',
                'unidad_medida' => 'kg',
                'stock_actual' => 18.500,
                'stock_minimo' => 8.000,
                'capacidad_maxima' => 45.000,
                'costo_unitario' => 38000.00,
                'proveedor_nombre' => 'Frigorífico Cárnicos Gourmet S.A.S.',
                'proveedor_nit' => '900.789.123-1',
                'proveedor_telefono' => '+57 310 456 7890',
                'ubicacion_almacen' => 'Cámara Fría #01 · Carnes',
                'temperatura_almacen' => '0°C - 2°C',
            ],
            [
                'nombre' => 'Ojo de Bife / Ribeye Angus',
                'codigo' => 'SKU-CAR-02',
                'categoria' => 'carnes',
                'unidad_medida' => 'kg',
                'stock_actual' => 15.000,
                'stock_minimo' => 6.000,
                'capacidad_maxima' => 35.000,
                'costo_unitario' => 46000.00,
                'proveedor_nombre' => 'Frigorífico Cárnicos Gourmet S.A.S.',
                'proveedor_nit' => '900.789.123-1',
                'proveedor_telefono' => '+57 310 456 7890',
                'ubicacion_almacen' => 'Cámara Fría #01 · Carnes',
                'temperatura_almacen' => '0°C - 2°C',
            ],
            [
                'nombre' => 'Costillar de Cerdo Seleccionado',
                'codigo' => 'SKU-CAR-03',
                'categoria' => 'carnes',
                'unidad_medida' => 'kg',
                'stock_actual' => 22.000,
                'stock_minimo' => 10.000,
                'capacidad_maxima' => 50.000,
                'costo_unitario' => 24000.00,
                'proveedor_nombre' => 'Distribuidora Porcina de Antioquia',
                'proveedor_nit' => '901.345.678-2',
                'proveedor_telefono' => '+57 312 345 6789',
                'ubicacion_almacen' => 'Cámara Congelación #02',
                'temperatura_almacen' => '-18°C',
            ],
            [
                'nombre' => 'Pechuga de Pollo Fresca Fileteada',
                'codigo' => 'SKU-CAR-04',
                'categoria' => 'carnes',
                'unidad_medida' => 'kg',
                'stock_actual' => 25.000,
                'stock_minimo' => 12.000,
                'capacidad_maxima' => 60.000,
                'costo_unitario' => 18000.00,
                'proveedor_nombre' => 'Avícola Santa Elena',
                'proveedor_nit' => '890.123.456-5',
                'proveedor_telefono' => '+57 315 678 9012',
                'ubicacion_almacen' => 'Cámara Fría #01 · Aves',
                'temperatura_almacen' => '2°C',
            ],
            [
                'nombre' => 'Carne Molida Especial Angus (80/20)',
                'codigo' => 'SKU-CAR-05',
                'categoria' => 'carnes',
                'unidad_medida' => 'kg',
                'stock_actual' => 30.000,
                'stock_minimo' => 15.000,
                'capacidad_maxima' => 70.000,
                'costo_unitario' => 22000.00,
                'proveedor_nombre' => 'Frigorífico Cárnicos Gourmet S.A.S.',
                'proveedor_nit' => '900.789.123-1',
                'proveedor_telefono' => '+57 310 456 7890',
                'ubicacion_almacen' => 'Cámara Fría #01',
                'temperatura_almacen' => '1°C',
            ],
            [
                'nombre' => 'Tocineta Ahumada Artesanal',
                'codigo' => 'SKU-CAR-06',
                'categoria' => 'carnes',
                'unidad_medida' => 'kg',
                'stock_actual' => 12.000,
                'stock_minimo' => 5.000,
                'capacidad_maxima' => 30.000,
                'costo_unitario' => 28000.00,
                'proveedor_nombre' => 'Embutidos del Valle',
                'proveedor_nit' => '900.654.321-7',
                'proveedor_telefono' => '+57 318 456 1234',
                'ubicacion_almacen' => 'Cámara Fría #01',
                'temperatura_almacen' => '4°C',
            ],
            [
                'nombre' => 'Pesca Blanca del Pacífico Fresca',
                'codigo' => 'SKU-PES-01',
                'categoria' => 'pescados',
                'unidad_medida' => 'kg',
                'stock_actual' => 8.500,
                'stock_minimo' => 5.000,
                'capacidad_maxima' => 25.000,
                'costo_unitario' => 34000.00,
                'proveedor_nombre' => 'Bahía Solano Seafood S.A.S.',
                'proveedor_nit' => '901.234.567-1',
                'proveedor_telefono' => '+57 310 456 7890',
                'ubicacion_almacen' => 'Cámara Fría Pescados',
                'temperatura_almacen' => '0°C - 2°C',
            ],
            [
                'nombre' => 'Camarones Tigre Pelados & Desvenados',
                'codigo' => 'SKU-PES-02',
                'categoria' => 'pescados',
                'unidad_medida' => 'kg',
                'stock_actual' => 10.000,
                'stock_minimo' => 5.000,
                'capacidad_maxima' => 30.000,
                'costo_unitario' => 42000.00,
                'proveedor_nombre' => 'Bahía Solano Seafood S.A.S.',
                'proveedor_nit' => '901.234.567-1',
                'proveedor_telefono' => '+57 310 456 7890',
                'ubicacion_almacen' => 'Cámara Congelación #02',
                'temperatura_almacen' => '-18°C',
            ],
            [
                'nombre' => 'Pan Brioche Artesanal Hamburguesa',
                'codigo' => 'SKU-PAN-01',
                'categoria' => 'panaderia',
                'unidad_medida' => 'unidad',
                'stock_actual' => 65.000,
                'stock_minimo' => 30.000,
                'capacidad_maxima' => 150.000,
                'costo_unitario' => 2200.00,
                'proveedor_nombre' => 'Panadería Masa Madre Provenza',
                'proveedor_nit' => '901.999.888-4',
                'proveedor_telefono' => '+57 301 234 5678',
                'ubicacion_almacen' => 'Almacén Seco · Estante Panadería',
                'temperatura_almacen' => 'Ambiente',
            ],
            [
                'nombre' => 'Pan Campesino Masa Madre',
                'codigo' => 'SKU-PAN-02',
                'categoria' => 'panaderia',
                'unidad_medida' => 'unidad',
                'stock_actual' => 25.000,
                'stock_minimo' => 10.000,
                'capacidad_maxima' => 60.000,
                'costo_unitario' => 3500.00,
                'proveedor_nombre' => 'Panadería Masa Madre Provenza',
                'proveedor_nit' => '901.999.888-4',
                'proveedor_telefono' => '+57 301 234 5678',
                'ubicacion_almacen' => 'Almacén Seco · Estante Panadería',
                'temperatura_almacen' => 'Ambiente',
            ],
            [
                'nombre' => 'Queso Cheddar Americano Madurado',
                'codigo' => 'SKU-LAC-01',
                'categoria' => 'lacteos_quesos',
                'unidad_medida' => 'kg',
                'stock_actual' => 14.000,
                'stock_minimo' => 6.000,
                'capacidad_maxima' => 35.000,
                'costo_unitario' => 32000.00,
                'proveedor_nombre' => 'Lácteos Andinos S.A.',
                'proveedor_nit' => '860.123.456-7',
                'proveedor_telefono' => '+57 300 445 6677',
                'ubicacion_almacen' => 'Cámara Lácteos #01',
                'temperatura_almacen' => '4°C',
            ],
            [
                'nombre' => 'Queso Parmesano Reggiano Rallado',
                'codigo' => 'SKU-LAC-02',
                'categoria' => 'lacteos_quesos',
                'unidad_medida' => 'kg',
                'stock_actual' => 8.000,
                'stock_minimo' => 4.000,
                'capacidad_maxima' => 20.000,
                'costo_unitario' => 58000.00,
                'proveedor_nombre' => 'Lácteos Andinos S.A.',
                'proveedor_nit' => '860.123.456-7',
                'proveedor_telefono' => '+57 300 445 6677',
                'ubicacion_almacen' => 'Cámara Lácteos #01',
                'temperatura_almacen' => '4°C',
            ],
            [
                'nombre' => 'Mozzarella di Bufala Fresca',
                'codigo' => 'SKU-LAC-03',
                'categoria' => 'lacteos_quesos',
                'unidad_medida' => 'kg',
                'stock_actual' => 9.500,
                'stock_minimo' => 5.000,
                'capacidad_maxima' => 25.000,
                'costo_unitario' => 36000.00,
                'proveedor_nombre' => 'Quesería Artesanal Campestre',
                'proveedor_nit' => '900.332.112-9',
                'proveedor_telefono' => '+57 311 223 3445',
                'ubicacion_almacen' => 'Cámara Lácteos #01',
                'temperatura_almacen' => '4°C',
            ],
            [
                'nombre' => 'Crema de Leche Gastronómica 35%',
                'codigo' => 'SKU-LAC-04',
                'categoria' => 'lacteos_quesos',
                'unidad_medida' => 'litro',
                'stock_actual' => 20.000,
                'stock_minimo' => 10.000,
                'capacidad_maxima' => 50.000,
                'costo_unitario' => 16000.00,
                'proveedor_nombre' => 'Lácteos Andinos S.A.',
                'proveedor_nit' => '860.123.456-7',
                'proveedor_telefono' => '+57 300 445 6677',
                'ubicacion_almacen' => 'Cámara Lácteos #01',
                'temperatura_almacen' => '4°C',
            ],
            [
                'nombre' => 'Queso Mascarpone Italiano',
                'codigo' => 'SKU-LAC-05',
                'categoria' => 'lacteos_quesos',
                'unidad_medida' => 'kg',
                'stock_actual' => 6.000,
                'stock_minimo' => 3.000,
                'capacidad_maxima' => 15.000,
                'costo_unitario' => 48000.00,
                'proveedor_nombre' => 'Importaciones Culinarias Europa',
                'proveedor_nit' => '901.889.001-3',
                'proveedor_telefono' => '+57 320 998 7766',
                'ubicacion_almacen' => 'Cámara Lácteos #01',
                'temperatura_almacen' => '3°C',
            ],
            [
                'nombre' => 'Pasta Fresca Artesanal Fettuccine',
                'codigo' => 'SKU-PAS-01',
                'categoria' => 'pastas_granos',
                'unidad_medida' => 'kg',
                'stock_actual' => 18.000,
                'stock_minimo' => 8.000,
                'capacidad_maxima' => 40.000,
                'costo_unitario' => 14000.00,
                'proveedor_nombre' => 'Pastificio Italiano Medellín',
                'proveedor_nit' => '900.443.221-8',
                'proveedor_telefono' => '+57 314 556 6778',
                'ubicacion_almacen' => 'Cámara Pasta Fresca',
                'temperatura_almacen' => '4°C',
            ],
            [
                'nombre' => 'Raviolis de Espinaca & Ricotta',
                'codigo' => 'SKU-PAS-02',
                'categoria' => 'pastas_granos',
                'unidad_medida' => 'kg',
                'stock_actual' => 12.000,
                'stock_minimo' => 5.000,
                'capacidad_maxima' => 30.000,
                'costo_unitario' => 19000.00,
                'proveedor_nombre' => 'Pastificio Italiano Medellín',
                'proveedor_nit' => '900.443.221-8',
                'proveedor_telefono' => '+57 314 556 6778',
                'ubicacion_almacen' => 'Cámara Congelación #02',
                'temperatura_almacen' => '-18°C',
            ],
            [
                'nombre' => 'Arroz Arborio para Risotto',
                'codigo' => 'SKU-PAS-03',
                'categoria' => 'pastas_granos',
                'unidad_medida' => 'kg',
                'stock_actual' => 25.000,
                'stock_minimo' => 10.000,
                'capacidad_maxima' => 60.000,
                'costo_unitario' => 18000.00,
                'proveedor_nombre' => 'Importaciones Culinarias Europa',
                'proveedor_nit' => '901.889.001-3',
                'proveedor_telefono' => '+57 320 998 7766',
                'ubicacion_almacen' => 'Almacén Seco · Tarima A2',
                'temperatura_almacen' => 'Ambiente seco',
            ],
            [
                'nombre' => 'Setas y Champiñones Portobello',
                'codigo' => 'SKU-VEG-01',
                'categoria' => 'vegetales',
                'unidad_medida' => 'kg',
                'stock_actual' => 14.000,
                'stock_minimo' => 6.000,
                'capacidad_maxima' => 30.000,
                'costo_unitario' => 22000.00,
                'proveedor_nombre' => 'Cultivos Orgánicos del Oriente',
                'proveedor_nit' => '900.556.778-4',
                'proveedor_telefono' => '+57 318 776 5544',
                'ubicacion_almacen' => 'Cámara de Verduras',
                'temperatura_almacen' => '6°C',
            ],
            [
                'nombre' => 'Rúgula y Espinacas Baby Hidropónicas',
                'codigo' => 'SKU-VEG-02',
                'categoria' => 'vegetales',
                'unidad_medida' => 'kg',
                'stock_actual' => 9.000,
                'stock_minimo' => 4.000,
                'capacidad_maxima' => 20.000,
                'costo_unitario' => 12000.00,
                'proveedor_nombre' => 'Cultivos Orgánicos del Oriente',
                'proveedor_nit' => '900.556.778-4',
                'proveedor_telefono' => '+57 318 776 5544',
                'ubicacion_almacen' => 'Cámara de Verduras',
                'temperatura_almacen' => '6°C',
            ],
            [
                'nombre' => 'Tomates Cherry y Chonto Seleccionados',
                'codigo' => 'SKU-VEG-03',
                'categoria' => 'vegetales',
                'unidad_medida' => 'kg',
                'stock_actual' => 16.000,
                'stock_minimo' => 8.000,
                'capacidad_maxima' => 40.000,
                'costo_unitario' => 8500.00,
                'proveedor_nombre' => 'Agrícola San Cristóbal',
                'proveedor_nit' => '900.111.222-3',
                'proveedor_telefono' => '+57 319 888 7766',
                'ubicacion_almacen' => 'Cámara de Verduras',
                'temperatura_almacen' => '8°C',
            ],
            [
                'nombre' => 'Papas Rústicas Pastusas',
                'codigo' => 'SKU-VEG-05',
                'categoria' => 'vegetales',
                'unidad_medida' => 'kg',
                'stock_actual' => 45.000,
                'stock_minimo' => 20.000,
                'capacidad_maxima' => 100.000,
                'costo_unitario' => 3800.00,
                'proveedor_nombre' => 'Central Mayorista de Antioquia',
                'proveedor_nit' => '890.999.000-1',
                'proveedor_telefono' => '+57 300 777 8899',
                'ubicacion_almacen' => 'Almacén de Tubérculos',
                'temperatura_almacen' => 'Ambiente fresco',
            ],
            [
                'nombre' => 'Aceite de Oliva con Esencia de Trufa',
                'codigo' => 'SKU-ACE-01',
                'categoria' => 'aceites_salsas',
                'unidad_medida' => 'litro',
                'stock_actual' => 8.000,
                'stock_minimo' => 4.000,
                'capacidad_maxima' => 20.000,
                'costo_unitario' => 65000.00,
                'proveedor_nombre' => 'Importaciones Culinarias Europa',
                'proveedor_nit' => '901.889.001-3',
                'proveedor_telefono' => '+57 320 998 7766',
                'ubicacion_almacen' => 'Almacén Seco · Bodega Gourmet',
                'temperatura_almacen' => 'Ambiente seco',
            ],
            [
                'nombre' => 'Salsa BBQ Artesanal de Panela & Ron',
                'codigo' => 'SKU-SAL-01',
                'categoria' => 'aceites_salsas',
                'unidad_medida' => 'litro',
                'stock_actual' => 15.000,
                'stock_minimo' => 5.000,
                'capacidad_maxima' => 35.000,
                'costo_unitario' => 15000.00,
                'proveedor_nombre' => 'Salsas & Sabores del Chef',
                'proveedor_nit' => '901.444.555-6',
                'proveedor_telefono' => '+57 316 777 6655',
                'ubicacion_almacen' => 'Almacén Seco · Despensa Salsas',
                'temperatura_almacen' => 'Ambiente',
            ],
            [
                'nombre' => 'Salsa Pomodoro Italiana al Albahaca',
                'codigo' => 'SKU-SAL-02',
                'categoria' => 'aceites_salsas',
                'unidad_medida' => 'litro',
                'stock_actual' => 18.000,
                'stock_minimo' => 8.000,
                'capacidad_maxima' => 40.000,
                'costo_unitario' => 12000.00,
                'proveedor_nombre' => 'Pastificio Italiano Medellín',
                'proveedor_nit' => '900.443.221-8',
                'proveedor_telefono' => '+57 314 556 6778',
                'ubicacion_almacen' => 'Almacén Seco · Despensa Salsas',
                'temperatura_almacen' => 'Ambiente',
            ],
            [
                'nombre' => 'Chocolate Amargo 70% Cacao',
                'codigo' => 'SKU-REP-01',
                'categoria' => 'reposteria',
                'unidad_medida' => 'kg',
                'stock_actual' => 12.000,
                'stock_minimo' => 5.000,
                'capacidad_maxima' => 30.000,
                'costo_unitario' => 38000.00,
                'proveedor_nombre' => 'Cacao Fino de Aroma Tumaco',
                'proveedor_nit' => '901.777.333-2',
                'proveedor_telefono' => '+57 317 222 1100',
                'ubicacion_almacen' => 'Almacén Seco Repostería',
                'temperatura_almacen' => '18°C',
            ],
            [
                'nombre' => 'Ginebra London Dry Premium',
                'codigo' => 'SKU-LIC-01',
                'categoria' => 'licores',
                'unidad_medida' => 'botella',
                'stock_actual' => 14.000,
                'stock_minimo' => 6.000,
                'capacidad_maxima' => 35.000,
                'costo_unitario' => 85000.00,
                'proveedor_nombre' => 'Distribuidora Licores del Río',
                'proveedor_nit' => '800.555.444-9',
                'proveedor_telefono' => '+57 300 888 9900',
                'ubicacion_almacen' => 'Cava de Licores & Barra',
                'temperatura_almacen' => 'Ambiente',
            ],
            [
                'nombre' => 'Ron Añejo Colombiano 8 Años',
                'codigo' => 'SKU-LIC-02',
                'categoria' => 'licores',
                'unidad_medida' => 'botella',
                'stock_actual' => 16.000,
                'stock_minimo' => 6.000,
                'capacidad_maxima' => 40.000,
                'costo_unitario' => 72000.00,
                'proveedor_nombre' => 'Fábrica de Licores de Antioquia',
                'proveedor_nit' => '890.900.286-0',
                'proveedor_telefono' => '+57 300 111 9988',
                'ubicacion_almacen' => 'Cava de Licores & Barra',
                'temperatura_almacen' => 'Ambiente',
            ],
            [
                'nombre' => 'Cajas Térmicas Ecodegradables Delivery',
                'codigo' => 'SKU-EMP-01',
                'categoria' => 'empaques',
                'unidad_medida' => 'unidad',
                'stock_actual' => 120.000,
                'stock_minimo' => 50.000,
                'capacidad_maxima' => 300.000,
                'costo_unitario' => 1200.00,
                'proveedor_nombre' => 'EcoEmpaques Colombia S.A.S.',
                'proveedor_nit' => '901.222.333-8',
                'proveedor_telefono' => '+57 312 999 8877',
                'ubicacion_almacen' => 'Almacén de Empaques',
                'temperatura_almacen' => 'Ambiente seco',
            ],
        ];

        $insumosMap = [];
        foreach ($insumosData as $item) {
            $insumo = Insumo::updateOrCreate(['codigo' => $item['codigo']], $item);
            $insumosMap[$item['codigo']] = $insumo;
        }

        // 2. Vincular Recetas (Escandallos) a los Platos del Menú
        $productos = Producto::all()->keyBy('nombre');

        $recetasConfig = [
            'Carpaccio de Res Trufado' => [
                ['codigo' => 'SKU-CAR-01', 'cantidad' => 0.120, 'merma' => 4.0, 'notas' => 'Láminas finas lomo de res'],
                ['codigo' => 'SKU-VEG-02', 'cantidad' => 0.030, 'merma' => 2.0, 'notas' => 'Cama de rúgula fresca'],
                ['codigo' => 'SKU-LAC-02', 'cantidad' => 0.025, 'merma' => 0.0, 'notas' => 'Lascas parmesano reggiano'],
                ['codigo' => 'SKU-ACE-01', 'cantidad' => 0.015, 'merma' => 0.0, 'notas' => 'Aceite trufado'],
            ],
            'Ceviche Mixto de la Casa' => [
                ['codigo' => 'SKU-PES-01', 'cantidad' => 0.100, 'merma' => 5.0, 'notas' => 'Cubos pesca fresca'],
                ['codigo' => 'SKU-PES-02', 'cantidad' => 0.060, 'merma' => 3.0, 'notas' => 'Camarones desvenados'],
            ],
            'Bruschettas Rústicas (3 pzs)' => [
                ['codigo' => 'SKU-PAN-02', 'cantidad' => 1.000, 'merma' => 0.0, 'notas' => '3 rebanadas pan campesino'],
                ['codigo' => 'SKU-VEG-03', 'cantidad' => 0.080, 'merma' => 2.0, 'notas' => 'Tomates cherry confitados'],
                ['codigo' => 'SKU-LAC-03', 'cantidad' => 0.060, 'merma' => 1.0, 'notas' => 'Mozzarella di bufala'],
            ],
            'Empanaditas de Punta de Anca (4 pzs)' => [
                ['codigo' => 'SKU-CAR-01', 'cantidad' => 0.100, 'merma' => 4.0, 'notas' => 'Carne punta de anca braseada'],
            ],
            'Bife de Chorizo Angus (350g)' => [
                ['codigo' => 'SKU-CAR-01', 'cantidad' => 0.380, 'merma' => 5.0, 'notas' => 'Corte crudo 380g para 350g neto'],
                ['codigo' => 'SKU-VEG-05', 'cantidad' => 0.200, 'merma' => 3.0, 'notas' => 'Papas rústicas al romero'],
            ],
            'Ojo de Bife / Ribeye (400g)' => [
                ['codigo' => 'SKU-CAR-02', 'cantidad' => 0.430, 'merma' => 5.0, 'notas' => 'Corte ribeye marmoleado'],
                ['codigo' => 'SKU-VEG-05', 'cantidad' => 0.200, 'merma' => 3.0, 'notas' => 'Papas rústicas guarnición'],
            ],
            'Costillas BBQ Ahumadas (500g)' => [
                ['codigo' => 'SKU-CAR-03', 'cantidad' => 0.550, 'merma' => 6.0, 'notas' => 'Costillar crudo marinado'],
                ['codigo' => 'SKU-SAL-01', 'cantidad' => 0.080, 'merma' => 1.0, 'notas' => 'Glaseado BBQ panela & ron'],
                ['codigo' => 'SKU-VEG-05', 'cantidad' => 0.150, 'merma' => 2.0, 'notas' => 'Papas'],
            ],
            'Pechuga Gratinada al Parmesano' => [
                ['codigo' => 'SKU-CAR-04', 'cantidad' => 0.250, 'merma' => 3.0, 'notas' => 'Pechuga fileteada'],
                ['codigo' => 'SKU-LAC-04', 'cantidad' => 0.060, 'merma' => 1.0, 'notas' => 'Salsa crema espinaca'],
                ['codigo' => 'SKU-LAC-02', 'cantidad' => 0.035, 'merma' => 0.0, 'notas' => 'Gratinado parmesano'],
            ],
            'Fettuccine Alfredo con Pollo & Champiñones' => [
                ['codigo' => 'SKU-PAS-01', 'cantidad' => 0.180, 'merma' => 2.0, 'notas' => 'Pasta fresca'],
                ['codigo' => 'SKU-CAR-04', 'cantidad' => 0.120, 'merma' => 3.0, 'notas' => 'Pollo en tiras'],
                ['codigo' => 'SKU-VEG-01', 'cantidad' => 0.060, 'merma' => 2.0, 'notas' => 'Portobello salteado'],
                ['codigo' => 'SKU-LAC-04', 'cantidad' => 0.080, 'merma' => 1.0, 'notas' => 'Crema de leche'],
                ['codigo' => 'SKU-LAC-02', 'cantidad' => 0.030, 'merma' => 0.0, 'notas' => 'Parmesano reggiano'],
            ],
            'Raviolis de Espinaca & Ricotta' => [
                ['codigo' => 'SKU-PAS-02', 'cantidad' => 0.220, 'merma' => 2.0, 'notas' => 'Raviolis frescos'],
                ['codigo' => 'SKU-SAL-02', 'cantidad' => 0.100, 'merma' => 1.0, 'notas' => 'Salsa pomodoro'],
                ['codigo' => 'SKU-LAC-02', 'cantidad' => 0.020, 'merma' => 0.0, 'notas' => 'Parmesano espolvoreado'],
            ],
            'Risotto de Setas Silvestres & Trufa' => [
                ['codigo' => 'SKU-PAS-03', 'cantidad' => 0.100, 'merma' => 1.0, 'notas' => 'Arroz arborio'],
                ['codigo' => 'SKU-VEG-01', 'cantidad' => 0.080, 'merma' => 3.0, 'notas' => 'Hongos portobello'],
                ['codigo' => 'SKU-ACE-01', 'cantidad' => 0.015, 'merma' => 0.0, 'notas' => 'Aceite de trufa toque'],
                ['codigo' => 'SKU-LAC-02', 'cantidad' => 0.030, 'merma' => 0.0, 'notas' => 'Parmesano mantecatura'],
            ],
            'RestoMaster Burger Master' => [
                ['codigo' => 'SKU-CAR-05', 'cantidad' => 0.210, 'merma' => 4.0, 'notas' => 'Carne molida angus 200g'],
                ['codigo' => 'SKU-PAN-01', 'cantidad' => 1.000, 'merma' => 0.0, 'notas' => 'Pan brioche tostado'],
                ['codigo' => 'SKU-CAR-06', 'cantidad' => 0.045, 'merma' => 5.0, 'notas' => '2 tiras tocineta ahumada'],
                ['codigo' => 'SKU-LAC-01', 'cantidad' => 0.040, 'merma' => 0.0, 'notas' => '2 lonchas cheddar'],
                ['codigo' => 'SKU-VEG-05', 'cantidad' => 0.150, 'merma' => 2.0, 'notas' => 'Papas rústicas'],
            ],
            'Hamburguesa Doble Trufa & Hongos' => [
                ['codigo' => 'SKU-CAR-05', 'cantidad' => 0.210, 'merma' => 4.0, 'notas' => '2 smash patties de 100g'],
                ['codigo' => 'SKU-PAN-01', 'cantidad' => 1.000, 'merma' => 0.0, 'notas' => 'Pan brioche'],
                ['codigo' => 'SKU-VEG-01', 'cantidad' => 0.050, 'merma' => 2.0, 'notas' => 'Hongos salteados'],
                ['codigo' => 'SKU-ACE-01', 'cantidad' => 0.010, 'merma' => 0.0, 'notas' => 'Mayo trufada'],
            ],
            'Volcán de Chocolate Fondant' => [
                ['codigo' => 'SKU-REP-01', 'cantidad' => 0.080, 'merma' => 2.0, 'notas' => 'Chocolate 70% cacao'],
                ['codigo' => 'SKU-LAC-04', 'cantidad' => 0.030, 'merma' => 1.0, 'notas' => 'Crema batida'],
            ],
            'Tiramisú Tradicional al Mascarpone' => [
                ['codigo' => 'SKU-LAC-05', 'cantidad' => 0.090, 'merma' => 1.0, 'notas' => 'Queso mascarpone'],
                ['codigo' => 'SKU-REP-01', 'cantidad' => 0.015, 'merma' => 0.0, 'notas' => 'Cacao amargo espolvoreado'],
            ],
            'Gin Tonic Cítrico & Frutos Rojos' => [
                ['codigo' => 'SKU-LIC-01', 'cantidad' => 0.060, 'merma' => 1.0, 'notas' => '2 oz Ginebra London Dry'],
            ],
            'Mojito Clásico de Ron Añejo' => [
                ['codigo' => 'SKU-LIC-02', 'cantidad' => 0.060, 'merma' => 1.0, 'notas' => '2 oz Ron añejo'],
            ],
        ];

        foreach ($recetasConfig as $productoNombre => $ingredientes) {
            if (! isset($productos[$productoNombre])) {
                continue;
            }
            $producto = $productos[$productoNombre];

            foreach ($ingredientes as $item) {
                if (isset($insumosMap[$item['codigo']])) {
                    Receta::updateOrCreate([
                        'producto_id' => $producto->id,
                        'insumo_id' => $insumosMap[$item['codigo']]->id,
                    ], [
                        'cantidad' => $item['cantidad'],
                        'merma_esperada_pct' => $item['merma'],
                        'notas' => $item['notas'],
                    ]);
                }
            }
        }

        // 3. Historial de Movimientos para Kardex & Informes
        $lomo = $insumosMap['SKU-CAR-01'];
        $carneMolida = $insumosMap['SKU-CAR-05'];
        $panBrioche = $insumosMap['SKU-PAN-01'];

        // Compra inicial
        MovimientoInventario::create([
            'insumo_id' => $lomo->id,
            'tipo' => 'compra',
            'cantidad' => 25.000,
            'saldo_anterior' => 0,
            'saldo_posterior' => 25.000,
            'costo_unitario' => 38000.00,
            'costo_total' => 950000.00,
            'user_id' => $admin?->id,
            'motivo' => 'Factura Guía #5840 - Frigorífico Cárnicos Gourmet S.A.S.',
            'referencia_documento' => 'FAC-5840',
            'created_at' => now()->subHours(8),
        ]);

        // Consumos por ventas
        $consumosMock = [
            ['insumo' => $lomo, 'qty' => 3.800, 'motivo' => 'Consumo COC-01 comanda #101 (Bife de Chorizo x 10)', 'horas' => 5],
            ['insumo' => $lomo, 'qty' => 2.400, 'motivo' => 'Consumo COC-01 comanda #104 (Carpaccio de Res x 20)', 'horas' => 4],
            ['insumo' => $carneMolida, 'qty' => 6.300, 'motivo' => 'Consumo COC-01 comanda #109 (Burger Master x 30)', 'horas' => 2],
            ['insumo' => $panBrioche, 'qty' => 30.000, 'motivo' => 'Consumo panadería despacho burgers turno tarde', 'horas' => 2],
        ];

        foreach ($consumosMock as $c) {
            $insumo = $c['insumo'];
            $costoTotal = round($c['qty'] * (float) $insumo->costo_unitario, 2);
            MovimientoInventario::create([
                'insumo_id' => $insumo->id,
                'tipo' => 'consumo_venta',
                'cantidad' => $c['qty'],
                'saldo_anterior' => (float) $insumo->stock_actual + $c['qty'],
                'saldo_posterior' => (float) $insumo->stock_actual,
                'costo_unitario' => $insumo->costo_unitario,
                'costo_total' => $costoTotal,
                'user_id' => $admin?->id,
                'motivo' => $c['motivo'],
                'referencia_documento' => 'KDS-ORD-'.rand(100, 200),
                'created_at' => now()->subHours($c['horas']),
            ]);
        }

        // Mermas reportadas
        MovimientoInventario::create([
            'insumo_id' => $lomo->id,
            'tipo' => 'merma',
            'cantidad' => 0.450,
            'saldo_anterior' => 18.950,
            'saldo_posterior' => 18.500,
            'costo_unitario' => 38000.00,
            'costo_total' => 17100.00,
            'user_id' => $admin?->id,
            'motivo' => 'Merma de limpieza y perfilado de grasa de lomo angus',
            'referencia_documento' => 'MER-001',
            'created_at' => now()->subHours(1),
        ]);
    }
}
