<?php

return [
    'catalogo' => [
        'pedidos.ver' => ['modulo' => 'Pedidos', 'label' => 'Ver comandas'],
        'pedidos.crear' => ['modulo' => 'Pedidos', 'label' => 'Crear pedidos'],
        'pedidos.actualizar' => ['modulo' => 'Pedidos', 'label' => 'Modificar pedidos'],
        'pedidos.eliminar' => ['modulo' => 'Pedidos', 'label' => 'Eliminar pedidos'],
        'pedidos.cobrar' => ['modulo' => 'Pedidos', 'label' => 'Cobrar (procesar cobro)'],
        'pedidos.enviar_cocina' => ['modulo' => 'Pedidos', 'label' => 'Enviar comanda a cocina'],
        'pedidos.aplicar_descuento' => ['modulo' => 'Pedidos', 'label' => 'Aplicar descuentos'],
        'pedidos.canjear_puntos' => ['modulo' => 'Pedidos', 'label' => 'Canjear puntos'],
        'pedidos.gestionar_delivery' => ['modulo' => 'Pedidos', 'label' => 'Gestionar delivery'],
        'mesas.ver' => ['modulo' => 'Mesas', 'label' => 'Ver mesas'],
        'mesas.crear' => ['modulo' => 'Mesas', 'label' => 'Crear mesas'],
        'mesas.actualizar' => ['modulo' => 'Mesas', 'label' => 'Editar mesas'],
        'mesas.eliminar' => ['modulo' => 'Mesas', 'label' => 'Eliminar mesas'],
        'mesas.cambiar_estado' => ['modulo' => 'Mesas', 'label' => 'Cambiar estado operativo'],
        'caja.ver' => ['modulo' => 'Caja', 'label' => 'Ver cajas'],
        'caja.crear' => ['modulo' => 'Caja', 'label' => 'Crear cajas/terminales'],
        'caja.actualizar' => ['modulo' => 'Caja', 'label' => 'Editar cajas'],
        'caja.eliminar' => ['modulo' => 'Caja', 'label' => 'Eliminar cajas'],
        'turnos.ver' => ['modulo' => 'Turnos', 'label' => 'Ver turnos'],
        'turnos.abrir' => ['modulo' => 'Turnos', 'label' => 'Abrir turno'],
        'turnos.cerrar' => ['modulo' => 'Turnos', 'label' => 'Cerrar turno'],
        'turnos.arqueo' => ['modulo' => 'Turnos', 'label' => 'Arqueo'],
        'turnos.guardar_movimiento' => ['modulo' => 'Turnos', 'label' => 'Registrar movimientos'],
        'clientes.ver' => ['modulo' => 'Clientes', 'label' => 'Ver clientes'],
        'clientes.crear' => ['modulo' => 'Clientes', 'label' => 'Crear clientes'],
        'clientes.actualizar' => ['modulo' => 'Clientes', 'label' => 'Editar clientes'],
        'clientes.eliminar' => ['modulo' => 'Clientes', 'label' => 'Eliminar clientes'],
        'clientes.ajustar_puntos' => ['modulo' => 'Clientes', 'label' => 'Ajustar puntos'],
        'reservas.ver' => ['modulo' => 'Reservas', 'label' => 'Ver reservas'],
        'reservas.crear' => ['modulo' => 'Reservas', 'label' => 'Crear reservas'],
        'reservas.actualizar' => ['modulo' => 'Reservas', 'label' => 'Editar reservas'],
        'reservas.eliminar' => ['modulo' => 'Reservas', 'label' => 'Eliminar reservas'],
        'reservas.confirmar' => ['modulo' => 'Reservas', 'label' => 'Confirmar reservas'],
        'reservas.cancelar' => ['modulo' => 'Reservas', 'label' => 'Cancelar reservas'],
        'insumos.ver' => ['modulo' => 'Inventario', 'label' => 'Ver insumos'],
        'insumos.crear' => ['modulo' => 'Inventario', 'label' => 'Crear insumos'],
        'insumos.actualizar' => ['modulo' => 'Inventario', 'label' => 'Editar insumos'],
        'insumos.eliminar' => ['modulo' => 'Inventario', 'label' => 'Eliminar insumos'],
        'insumos.registrar_compra' => ['modulo' => 'Inventario', 'label' => 'Registrar compra'],
        'insumos.registrar_merma' => ['modulo' => 'Inventario', 'label' => 'Registrar merma'],
        'insumos.ajuste_fisico' => ['modulo' => 'Inventario', 'label' => 'Ajuste físico'],
        'cxp.ver' => ['modulo' => 'CxP', 'label' => 'Ver cuentas por pagar'],
        'cxp.crear' => ['modulo' => 'CxP', 'label' => 'Crear cuentas por pagar'],
        'cxp.actualizar' => ['modulo' => 'CxP', 'label' => 'Editar cuentas por pagar'],
        'cxp.eliminar' => ['modulo' => 'CxP', 'label' => 'Eliminar cuentas por pagar'],
        'cxp.registrar_pago' => ['modulo' => 'CxP', 'label' => 'Registrar pago'],
        'proveedores.ver' => ['modulo' => 'Proveedores', 'label' => 'Ver proveedores'],
        'proveedores.crear' => ['modulo' => 'Proveedores', 'label' => 'Crear proveedores'],
        'proveedores.actualizar' => ['modulo' => 'Proveedores', 'label' => 'Editar proveedores'],
        'proveedores.eliminar' => ['modulo' => 'Proveedores', 'label' => 'Eliminar proveedores'],
        'compras.ver' => ['modulo' => 'Compras', 'label' => 'Ver compras'],
        'compras.crear' => ['modulo' => 'Compras', 'label' => 'Registrar factura'],
        'compras.anular' => ['modulo' => 'Compras', 'label' => 'Anular factura'],
    ],
    'mapa' => [
        'Pedido' => 'pedidos', 'Mesa' => 'mesas', 'Caja' => 'caja',
        'TurnoCaja' => 'turnos', 'Cliente' => 'clientes', 'Reserva' => 'reservas',
        'Insumo' => 'insumos', 'CuentaPorPagar' => 'cxp',
        'Proveedor' => 'proveedores', 'Compra' => 'compras',
    ],
    'plantillas' => [
        'admin' => '*',
        'gerente' => [
            'pedidos.ver', 'pedidos.crear', 'pedidos.actualizar', 'pedidos.eliminar', 'pedidos.cobrar', 'pedidos.enviar_cocina', 'pedidos.aplicar_descuento', 'pedidos.canjear_puntos', 'pedidos.gestionar_delivery',
            'mesas.ver', 'mesas.crear', 'mesas.actualizar', 'mesas.eliminar', 'mesas.cambiar_estado',
            'caja.ver', 'caja.crear', 'caja.actualizar',
            'turnos.ver', 'turnos.abrir', 'turnos.cerrar', 'turnos.arqueo', 'turnos.guardar_movimiento',
            'clientes.ver', 'clientes.crear', 'clientes.actualizar', 'clientes.eliminar', 'clientes.ajustar_puntos',
            'reservas.ver', 'reservas.crear', 'reservas.actualizar', 'reservas.eliminar', 'reservas.confirmar', 'reservas.cancelar',
            'insumos.ver', 'insumos.crear', 'insumos.actualizar', 'insumos.eliminar', 'insumos.registrar_compra', 'insumos.registrar_merma', 'insumos.ajuste_fisico',
            'cxp.ver', 'cxp.crear', 'cxp.actualizar', 'cxp.eliminar', 'cxp.registrar_pago',
            'proveedores.ver', 'proveedores.crear', 'proveedores.actualizar', 'proveedores.eliminar',
            'compras.ver', 'compras.crear', 'compras.anular',
        ],
        'cajero' => [
            'pedidos.ver', 'pedidos.crear', 'pedidos.actualizar', 'pedidos.cobrar', 'pedidos.enviar_cocina', 'pedidos.aplicar_descuento', 'pedidos.canjear_puntos', 'pedidos.gestionar_delivery',
            'mesas.ver', 'mesas.cambiar_estado',
            'caja.ver',
            'turnos.ver', 'turnos.abrir', 'turnos.cerrar', 'turnos.arqueo', 'turnos.guardar_movimiento',
            'clientes.ver', 'clientes.crear', 'clientes.actualizar', 'clientes.ajustar_puntos',
            'reservas.ver', 'reservas.crear', 'reservas.actualizar', 'reservas.confirmar', 'reservas.cancelar',
        ],
        'mesero' => [
            'pedidos.ver', 'pedidos.crear', 'pedidos.actualizar', 'pedidos.cobrar', 'pedidos.enviar_cocina', 'pedidos.canjear_puntos',
            'mesas.ver', 'mesas.cambiar_estado',
            'reservas.ver', 'reservas.crear', 'reservas.actualizar', 'reservas.confirmar', 'reservas.cancelar',
        ],
        'cocina' => ['pedidos.ver'],
        'barra' => ['pedidos.ver'],
        'delivery' => ['pedidos.ver', 'pedidos.gestionar_delivery'],
    ],
];
